export const environment = {
    AWS_REGION: process.env.AWS_REGION,
    CONNECTIONS_TABLE_NAME: process.env.CONNECTIONS_TABLE_NAME,

    BOLD_CLIENT_ID: process.env.BOLD_CLIENT_ID,
    BOLD_CLIENT_SECRET: process.env.BOLD_CLIENT_SECRET,
    BOLD_REDIRECT_URI: process.env.BOLD_REDIRECT_URI,

    WEBSOCKET_MANAGEMENT_ENDPOINT: process.env.WEBSOCKET_MANAGEMENT_ENDPOINT
};